title: botStuff - Public
description: Front-facing botStuff.org 
show_downloads: false
google_analytics:
theme: jekyll-theme-leap-day
jekyll_admin:
  hidden_links:
    - posts
    - pages
    - staticfiles
    - datafiles
    - configuration
  homepage: "pages"
plugins:
  - jekyll-feed